config/routes.rb
Blog::Application.routes.draw do
  root to: "welcome#index"
  
  resources :posts do
    resources :comments
  end

  get 'books/list'  # should be first
  resources :books do
  end

  

end

app/models/book.rb
class Book < ActiveRecord::Base
    validates :title, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    http_basic_authenticate_with name: "rabierre", password: "1shdlfm", except:[:index, :show]

    def index
        @books = Book.find(:all, :order => "id desc", :limit => 3)
    end

    def list
        @books = Book.all
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(params[:book].permit(:title, :author, :summary))

        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def show
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        # todo not delete Book but inactivate
        @book.delete

        redirect_to books_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:commenter, :body))

        redirect_to post_path(@post)
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.delete

        redirect_to post_path(@post)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "rabierre", password: "1shdlfm", except:[:index, :show]
    
  def new
    @post = Post.new
  end

  def create
    #render text: params[:post].inspect # this cause double render error

    @post = Post.new(params[:post].permit(:title, :text))

    if @post.save
        redirect_to @post
    else
        render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :text))
        redirect_to @post
    else
        render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete

    redirect_to posts_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@book.errors.count, "error") %> 
    prohibited this book from being saved:
    </h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :summary %>    
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/index.html.erb
<div id="wrapper">

<%= render "layouts/menu" %>

<div id="content">
    <h2>Recent Books</h2>
    <table>
        <% @books.each do |book| %>
            <tr>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.author %></td>
                <td><%= book.summary %></td>
                <td><%= link_to 'Delete', book_path(book),
                                method: :delete, data: {confirm: 'Really Remove this book?'} %></td>
                
            </tr>
            <!-- 여기에 줄 긋기 -->
        <% end %>
    </table>
    <%= link_to 'New Book', new_book_path %>
    <%= link_to 'Book List', books_list_path %>

    <h2>Recent Reviews</h2>
    <%= render template: "books/list" %>
</div>
</div>

app/views/books/list.html.erb
<table>
    <tr>
        <th>All Books</th>
    </tr>

    <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= link_to 'Show', book_path(book) %></td>
        </tr>
        <!-- 여기에 줄 긋기 -->
    <% end %>
</table>
</div>

app/views/books/new.html.erb
<div id="wrapper">
    <%= render "layouts/head" %>
    <%= render "layouts/menu" %>

    <div id="content">
        <h1>Insert New Book Info</h1>
        
        <%= render 'form' %>
        <%= link_to 'Back', books_path %>
    </div>
</div>

app/views/books/review.html.erb
<% @books.each do |book| %>
    <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.summary %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <td><%= link_to 'Delete', book_path(book),
                        method: :delete, data: {confirm: 'Really Remove this book?'} %></td>
        
    </tr>
    <!-- 여기에 줄 긋기 -->
<% end %>

app/views/books/show.html.erb
<div id="wrapper">
<%= render "layouts/head" %>
<%= render "layouts/menu" %>

<div id="content">
    <p>
        <h2> Title:
        <%= @book.title %>
        </h2>
    </p>
    <p>
        <h2> Author:
        <%= @book.author %>
        </h2>
    </p>
    <p>
        <%= @book.summary %>
    </p>

    <%= link_to 'Edit', edit_book_path(@book) %>
</div>
</div>

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
</p>
<p>
    <strong>Comment:</strong>
    <%= comment.body %>
</p>

<p>
    <%= link_to 'Delete Comment', [comment.post, comment],
                method: :delete, data: {confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :commenter %><br />
        <%= f.text_field :commenter %>
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/_head.html.erb
<div id="header">
    <header>
        <hgroup>
            <p><%= link_to "Blog Home", root_path %></p>
            <p>subtitle</p>
        </hgroup>
    </header>
</div>

app/views/layouts/_menu.html.erb
<div id="menu">
    <strong>Menu</strong><br>

    <div id="linkbox">
        <ul>
        <li><%= link_to "blog", controller: "posts" %></li>
        <li><%= link_to "books", controller:"books" %></li>
        </ul>
    </div>
    <br>

    <div id="github-badge">
        <iframe src="http://githubbadge.appspot.com/badge/rabierre?s=1" style="border: 0;height: 142px;width: 200px;overflow: hidden;" frameBorder=0></iframe>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/head" %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> 
    prohibited this post from being saved:
    </h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>    
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="wrapper">
    <%= render "layouts/menu" %>

    <div id="content">
        <h1>Edit post</h1>

        <%= render 'form' %>

        <%= link_to 'Back', posts_path %>
    </div>
</div>

app/views/posts/index.html.erb
<div id="wrapper">
<%= render "layouts/menu" %>

<div id="content">
<%= link_to 'New Post', new_post_path %>

<table>
    <tr>
        <th>Title</th>
    </tr>

    <% @posts.each do |post| %>
        <tr>
            <td><%= post.title %></td>
            <td><%= link_to 'Show', post_path(post) %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Delete', post_path(post),
                            method: :delete, data: {confirm: 'Really Remove this post?'} %></td>
        </tr>
    <% end %>
</table>
</div>
</div>

app/views/posts/new.html.erb
<div id="wrapper">
    <%= render "layouts/menu" %>

    <div id="content">
        <h1>New Posts!</h1>

        <%= render 'form' %>
        <%= link_to 'Back', posts_path %>
    </div>
</div>

app/views/posts/show.html.erb
<div id="wrapper">
<%= render "layouts/menu" %>

<div id="content">
    <p>
        <h2> Title:
        <%= @post.title %>
        </h2>
    </p>
    <p>
        <%= @post.text %>
    </p>

    <div id="comment">
        <h2>Comments</h2>
        <%= render @post.comments %>

        <h2>Add a comment here</h2>
        <%= render "comments/form" %>
    </div>

    <%= link_to 'Back', posts_path %> |
    <%= link_to 'Edit', edit_post_path(@post) %>
</div>
</div>

app/views/welcome/index.html.erb
<div id="wrapper">
    <%= render "layouts/menu" %>

    <div id="content">
    <article>
        <hgroup>
        future features
        </hgroup>
        <dl>
            <dt>beautiful index page</dt>
            <dd>home page</dd>
            <dt>contact page</dt>
            <dd>site ower description page</dd>
            <dt>wiki</dt>
        </dl>
    </article>
    </div>
</div>
<!-- http://nirvdrum.com/ -->